### ISSUE TITLE
Organize examples by back-end

### ISSUE THREAD

**Issue by jacklinke** [rajasegar/awesome-htmx#14]
There are so many examples at this point that it might be beneficial to separate them by back-end.

Maybe group as follows:
- ASP.net
- Clojure
- Common Lisp
- Express
- Flask
- Python-based (Django, FastAPI, Flask)
- Ruby
- Other

This could of course be modified/expanded later as needed.

I'd be happy to submit a PR for this if it is seen as beneficial.

**Comment by rajasegar** [comment]
PR merged 👍
